name: Install Swift
description: Installs the Swift specified by a .swift-version file

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      shell: bash
      run: |
        mkdir -p "$HOME/.local/share"

        export SWIFTLY_TOOLCHAINS_DIR="$HOME/.local/share/swiftly/toolchains"
        echo "SWIFTLY_TOOLCHAINS_DIR=$SWIFTLY_TOOLCHAINS_DIR" >> $GITHUB_ENV
        echo "SWIFTLY_TOOLCHAINS_DIR=$SWIFTLY_TOOLCHAINS_DIR" >> $HOME/.bashrc

        export SWIFTLY_HOME_DIR="$HOME/.local/share/swiftly"
        echo "SWIFTLY_HOME_DIR=$SWIFTLY_HOME_DIR" >> $GITHUB_ENV
        echo "SWIFTLY_HOME_DIR=$SWIFTLY_HOME_DIR" >> $HOME/.bashrc

        export SWIFTLY_BIN_DIR="$HOME/.local/share/swiftly/bin"
        echo "SWIFTLY_BIN_DIR=$SWIFTLY_BIN_DIR" >> $GITHUB_ENV
        echo "SWIFTLY_BIN_DIR=$SWIFTLY_BIN_DIR" >> $HOME/.bashrc

        echo "PATH=$SWIFTLY_BIN_DIR:$PATH" >> $GITHUB_ENV
        echo "PATH=\$SWIFTLY_BIN_DIR:\$PATH" >> $HOME/.bashrc

    - name: Restore Swift
      uses: actions/cache/restore@v4
      id: cache-swift
      with:
        path: "~/.local/share/swiftly"
        key: swift-${{ runner.os }}-${{ hashFiles('**/.swift-version', '.github/actions/install-swift/action.yml') }}

    - name: Install `apt` Dependencies
      if: runner.os == 'Linux' && steps.cache-swift.outputs.cache-hit != 'true'
      shell: bash
      run: |
        SUDO=$(if [[ $EUID -ne 0 ]]; then echo sudo; fi)
        $SUDO apt-get -qq update
        $SUDO apt-get -qq -y install curl gpg
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Swiftly
      if: runner.os == 'Linux' && steps.cache-swift.outputs.cache-hit != 'true'
      shell: bash
      run: |
        SWIFTLY_VERSION=1.0.1
        UNAME=$(uname -m)
        SWIFTLY_TGZ=swiftly-$SWIFTLY_VERSION-$UNAME.tar.gz
        curl -O "https://download.swift.org/swiftly/linux/$SWIFTLY_TGZ"
        tar zxf "$SWIFTLY_TGZ"
        ./swiftly init \
          --skip-install \
          --assume-yes \
          --quiet-shell-followup \
          --no-modify-profile

    - name: Install Swiftly
      if: runner.os == 'macOS' && steps.cache-swift.outputs.cache-hit != 'true'
      shell: bash
      run: |
        SWIFTLY_VERSION=1.0.1
        SWIFTLY_PKG=swiftly-$SWIFTLY_VERSION.pkg
        curl -O "https://download.swift.org/swiftly/darwin/$SWIFTLY_PKG"
        pkgutil --check-signature $SWIFTLY_PKG
        pkgutil --verbose --expand $SWIFTLY_PKG $SWIFTLY_HOME_DIR
        tar -C $SWIFTLY_HOME_DIR -xvf $SWIFTLY_HOME_DIR/swiftly-*/Payload
        "$SWIFTLY_BIN_DIR/swiftly" init \
          --skip-install \
          --assume-yes \
          --quiet-shell-followup \
          --no-modify-profile

    - name: Install Swift
      if: steps.cache-swift.outputs.cache-hit != 'true'
      shell: bash
      run: swiftly install --post-install-file ./out.sh

    - name: Save Swift
      if: steps.cache-swift.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: "~/.local/share/swiftly"
        key: swift-${{ runner.os }}-${{ hashFiles('**/.swift-version', '.github/actions/install-swift/action.yml') }}

    - name: Print Swift Version
      shell: bash
      run: swift --version
