name: STM32 ELF

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        example: [stm32-blink, stm32-lvgl]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Swift
        uses: ./.github/actions/install-swift

      - name: Build ${{ matrix.example }}
        working-directory: ${{ matrix.example }}
        run: |
          if [[ -f ./fetch-dependencies.sh ]]; then
            ./fetch-dependencies.sh
          fi

          if [[ -f Makefile ]]; then
            make
          fi
