name: STM32 Macho

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: [self-hosted, macos, sequoia, ARM64]

    strategy:
      fail-fast: false
      matrix:
        example: [stm32-blink, stm32-lcd-logo, stm32-neopixel, stm32-uart-echo]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Swift
        uses: ./.github/actions/install-swift

      - name: Validate Swiftly Paths
        run: |
          echo "Swiftly Path: $SWIFTLY_HOME_DIR"
          echo "Swiftly Bin Path: $SWIFTLY_BIN_DIR"
          echo "Swiftly Lib Path: $SWIFTLY_TOOLCHAINS_DIR"

          ls -asl $SWIFTLY_HOME_DIR
          ls -asl $SWIFTLY_BIN_DIR
          ls -asl $SWIFTLY_TOOLCHAINS_DIR

          ls -asl $HOME/.local/share/swiftly

      - name: Build ${{ matrix.example }}
        working-directory: ${{ matrix.example }}
        run: make
